apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hetzner-nginx-ingress
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  destination:
    server: https://kubernetes.default.svc
  project: platform
  source:
    path: platform/hetzner-nginx-ingress
    repoURL: https://github.com/dbackeus/get-started.git
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
    syncOptions:
      - ServerSideApply=true
