resources:
  - ./namespace.yaml
helmCharts:
  - name: ingress-nginx
    repo: https://kubernetes.github.io/ingress-nginx
    releaseName: ingress-nginx
    version: 4.12.3 # App version 1.12.3
    namespace: ingress-nginx
    valuesInline:
      controller:
        kind: DaemonSet
        # replicaCount: 6
        # hostPort:
        #   enabled: true
        ingressClassResource:
          default: true
        service:
          annotations:
            load-balancer.hetzner.cloud/name: ingress-nginx
            load-balancer.hetzner.cloud/location: hel1
            load-balancer.hetzner.cloud/use-private-ip: "true"
            load-balancer.hetzner.cloud/uses-proxyprotocol: "false"
            load-balancer.hetzner.cloud/http-redirect-https: "false"
            load-balancer.hetzner.cloud/node-selector: node-role.kubernetes.io/worker=
            # load-balancer.hetzner.cloud/hostname: <hostname>
          externalTrafficPolicy: Cluster
          targetPorts:
            https: http
        # Reference: https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/configmap
        # config:
        #   use-proxy-protocol: "true"
