resources:
  - ./namespace.yaml
  - ./configmap.yaml
helmCharts:
  - name: ingress-nginx
    repo: https://kubernetes.github.io/ingress-nginx
    releaseName: ingress-nginx
    version: 4.12.3 # App version 1.12.3
    valuesInline:
      controller:
        kind: DaemonSet
        ingressClassResource:
          default: true
        service:
          annotations:
            load-balancer.hetzner.cloud/name: ingress-nginx
            load-balancer.hetzner.cloud/location: hel1
            load-balancer.hetzner.cloud/use-private-ip: "true"
            load-balancer.hetzner.cloud/uses-proxyprotocol: "true"
            load-balancer.hetzner.cloud/http-redirect-https: "false"
            load-balancer.hetzner.cloud/node-selector: "node-role.kubernetes.io/worker="
            # load-balancer.hetzner.cloud/hostname: <hostname>
          targetPorts:
            https: http
