# https://doc.traefik.io/traefik/providers/kubernetes-gateway/

resources:
  - ./namespace.yaml
helmCharts:
  - name: traefik
    repo: https://traefik.github.io/charts
    releaseName: traefik
    version: 36.2.0 # App version 3.4.1
    namespace: traefik
    includeCRDs: true
    valuesInline:
      providers:
        kubernetesGateway:
          enabled: true
      ports:
        web:
          forwardedHeaders:
            insecure: true
          proxyProtocol:
            insecure: true
      gateway:
        listeners:
          web:
            namespacePolicy: All
      deployment:
        kind: Deployment
        replicas: 1
      service:
        enabled: true
        spec:
          externalTrafficPolicy: Local
        annotations:
          load-balancer.hetzner.cloud/name: traefik-gateway
          load-balancer.hetzner.cloud/location: hel1
          load-balancer.hetzner.cloud/use-private-ip: "true"
          load-balancer.hetzner.cloud/uses-proxyprotocol: "true"
          load-balancer.hetzner.cloud/http-redirect-https: "false"
          load-balancer.hetzner.cloud/node-selector: node-role.kubernetes.io/worker=
          # load-balancer.hetzner.cloud/hostname: <hostname>
      logs:
        # general:
        #   level: DEBUG
        access:
          enabled: true
          format: json # only way to get the Host header
          fields:
            headers:
              defaultMode: drop
              names:
                Host: keep
